panda_hand_controller:
    type: position_controllers/JointTrajectoryController
    #publish_rate: 30  # [Hz]
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    #default_speed: 0.1  # [m/s]
